// react-frontend/src/components/Header.js
import React from 'react';
import { Link } from 'react-router-dom';

function Header() {
  return (
    <header className="app-header">
      <Link to="/">
        <h1>Data-Driven E-commerce MVP</h1>
      </Link>
      {/* Add navigation, user info, cart icon etc. */}
    </header>
  );
}

export default Header;

// vue-frontend/src/components/Header.vue
<template>
  <header class="app-header">
    <router-link to="/">
      <h1>Data-Driven E-commerce MVP</h1>
    </router-link>
    <!-- Add navigation, user info, cart icon etc. -->
  </header>
</template>

<style scoped>
.app-header {
  background-color: #f8f8f8;
  padding: 20px;
  border-bottom: 1px solid #eee;
}
h1 {
  margin: 0;
  color: #333;
}
a {
  text-decoration: none;
}
</style>
